### ISSUE TITLE
Migrations で指定できる全項目のサポート

### ISSUE THREAD

**Issue by ucan-lab** [ucan-lab/laravel-dacapo#15]
## 使用できるカラムタイプ

https://readouble.com/laravel/5.8/ja/migrations.html#creating-columns

- [x] `$table->bigIncrements('id');` // 符号なしBIGINTを使用した自動増分ID（主キー）
- [x] `$table->bigInteger('votes');` // BIGINTカラム
- [x] `$table->binary('data');` // BLOBカラム
- [x] `$table->boolean('confirmed');` // BOOLEANカラム
- [x] `$table->char('name', 100);` // オプションの文字長を指定するCHARカラム
- [x] `$table->date('created_at');` // DATEカラム
- [x] `$table->dateTime('created_at');` // DATETIMEカラム
- [x] `$table->dateTimeTz('created_at');` // タイムゾーン付きDATETIMEカラム
- [x] `$table->decimal('amount', 8, 2);` // 有効（全体桁数）／小数点以下桁数指定のDECIMALカラム
- [x] `$table->double('amount', 8, 2);` // 有効（全体桁数）／小数点以下桁数指定のDOUBLEカラム
- [x] `$table->enum('level', ['easy', 'hard']);` // ENUMカラム
- [x] `$table->float('amount', 8, 2);` // 有効（全体桁数）／小数点以下桁数指定のFLOATカラム
- [x] `$table->geometry('positions');` // GEOMETRYカラム
- [x] `$table->geometryCollection('positions');` // GEOMETRYCOLLECTIONカラム
- [x] `$table->increments('id');` // 符号なしINTを使用した自動増分ID（主キー）
- [x] `$table->integer('votes');` // INTEGERカラム
- [x] `$table->ipAddress('visitor');` // IPアドレスカラム
- [x] `$table->json('options');` // JSONフィールド
- [x] `$table->jsonb('options');` // JSONBフィールド
- [x] `$table->lineString('positions');` // LINESTRINGカラム
- [x] `$table->longText('description');` // LONGTEXTカラム
- [x] `$table->macAddress('device');` // MACアドレスカラム
- [x] `$table->mediumIncrements('id');` // 符号なしMEDIUMINTを使用した自動増分ID（主キー）
- [x] `$table->mediumInteger('votes');` // MEDIUMINTカラム
- [x] `$table->mediumText('description');` // MEDIUMTEXTカラム
- [x] `$table->morphs('taggable');` // 符号なしBIGINTのtaggable_idと文字列のtaggable_typeを追加
- [x] `$table->uuidMorphs('taggable');` // CHAR(36)のtaggable_idとVARCHAR(255)のtaggable_type UUIDカラムを追加
- [x] `$table->multiLineString('positions');` // MULTILINESTRINGカラム
- [x] `$table->multiPoint('positions');` // MULTIPOINTカラム
- [x] `$table->multiPolygon('positions');` // MULTIPOLYGONカラム
- [x] `$table->nullableMorphs('taggable');` // NULL値可能なmorphs()カラム
- [x] `$table->nullableUuidMorphs('taggable');` // uuidMorphs()をNULL値可能で追加
- [x] `$table->nullableTimestamps();` // timestamps()メソッドの別名
- [x] `$table->point('position');` // POINTカラム
- [x] `$table->polygon('positions');` // POLYGONカラム
- [x] `$table->rememberToken();` // VARCHAR(100)でNULL値可能なremember_tokenを追加
- [x] `$table->set('flavors', ['strawberry', 'vanilla']);` // SETカラム
- [x] `$table->smallIncrements('id');` // 符号なしSMALLINTを使用した自動増分ID（主キー）
- [x] `$table->smallInteger('votes');` // SMALLINTカラム
- [x] `$table->softDeletes();` // ソフトデリートのためにNULL値可能なdeleted_at TIMESTAMPカラム追加
- [x] `$table->softDeletesTz();` // ソフトデリートのためにNULL値可能なdeleted_atタイムゾーン付きTIMESTAMPカラム追加
- [x] `$table->string('name', 100);` // オプションの文字長を指定したVARCHARカラム
- [x] `$table->text('description');` // TEXTカラム
- [x] `$table->time('sunrise');` // TIMEカラム
- [x] `$table->timeTz('sunrise');` // タイムゾーン付きTIMEカラム
- [x] `$table->timestamp('added_on');` // TIMESTAMPカラム
- [x] `$table->timestampTz('added_on');` // タイムゾーン付きTIMESTAMPカラム
- [x] `$table->timestamps();` // NULL値可能なcreated_atとupdated_atカラム追加
- [x] `$table->timestampsTz();` // タイムゾーン付きのNULL値可能なcreated_atとupdated_atカラム追加
- [x] `$table->tinyIncrements('id');` // 符号なしTINYINTを使用した自動増分ID（主キー）
- [x] `$table->tinyInteger('votes');` // TINYINTカラム
- [x] `$table->unsignedBigInteger('votes');` // 符号なしBIGINTカラム
- [x] `$table->unsignedDecimal('amount', 8, 2);` // 有効（全体桁数）／小数点以下桁数指定の符号なしDECIMALカラム
- [x] `$table->unsignedInteger('votes');` // 符号なしINTカラム
- [x] `$table->unsignedMediumInteger('votes');` // 符号なしMEDIUMINTカラム
- [x] `$table->unsignedSmallInteger('votes');` // 符号なしSMALLINTカラム
- [x] `$table->unsignedTinyInteger('votes');` // 符号なしTINYINTカラム
- [x] `$table->uuid('id');` // UUIDカラム
- [x] `$table->year('birth_year');` // YEARカラム

## カラム修飾子

https://readouble.com/laravel/5.8/ja/migrations.html#column-modifiers

- [ ] `->after('column')` // 指定カラムの次に他のカラムを設置(MySQLのみ)
- [x] `->autoIncrement()` // 整数カラムを自動増分ID（主キー）へ設定
- [x] `->charset('utf8')` // カラムへキャラクタセットを指定(MySQLのみ)
- [x] `->collation('utf8_unicode_ci')` // カラムへコロケーションを指定(MySQL/PostgreSQL/SQL Serverのみ)
- [x] `->comment('my comment')` // カラムにコメント追加(MySQL/PostgreSQLのみ)
- [x] `->default($value)` // カラムのデフォルト(default)値設定
- [ ] `->first()` // カラムをテーブルの最初(first)に設置する(MySQLのみ)
- [x] `->nullable($value = true)` // （デフォルトで）NULL値をカラムに挿入する
- [x] `->storedAs($expression)` // stored generatedカラムを生成(MySQLのみ)
- [x] `->unsigned()` // 整数カラムを符号なしに設定(MySQLのみ)
- [x] `->useCurrent()` // TIMESTAMPカラムのデフォルト値をCURRENT_TIMESTAMPに指定
- [x] `->virtualAs($expression)` // virtual generatedカラムを生成(MySQLのみ)
- [x] `->generatedAs($expression)` // 指定のシーケンスオプションで、識別カラムを生成(PostgreSQLのみ)
- [x] `->always()` // 識別カラムの入力を上書きするシーケンス値を定義(PostgreSQLのみ)

**Comment by ucan-lab** [comment]
## 使用できるカラムタイプのテスト用のyml

`test_column_type.yml`

```
test_column_type1:
  columns:
    id:
      type: bigInteger
    votes:
      type: bigInteger
    data:
      type: binary
    confirmed:
      type: boolean
    name:
      type: char(100)
    created_date:
      type: date
    created_at:
      type: dateTime
    created_tz:
      type: dateTimeTz
    amount:
      type: decimal(8, 2)
    total:
      type: double(8, 2)
    level:
      type: enum(['easy', 'hard'])
    subtotal:
      type: float(8, 2)
    positions:
      type: geometry
    positions_collection:
      type: geometryCollection

test_column_type2:
  columns:
    id:
      type: increments
    votes:
      type: integer
    visitor:
      type: ipAddress
    options:
      type: json
    options_b:
      type: jsonb
    positions:
      type: lineString
    description:
      type: longText
    device:
      type: macAddress

test_column_type3:
  columns:
    id:
      type: mediumIncrements
    votes:
      type: mediumInteger
    description:
      type: mediumText
    taggable:
      type: morphs
    taggable_uuid:
      type: uuidMorphs
    positions_multi_line:
      type: multiLineString
    positions_multi_point:
      type: multiPoint
    positions_multi_polygon:
      type: multiPolygon
    taggable_nullable:
      type: nullableMorphs('custom_taggable_nullable_index')
    taggable_nullable_uuid:
      type: nullableMorphs('custom_taggable_nullable_nullable_morphs_index')
    position_point:
      type: point
    positions_polygon:
      type: polygon
    flavors:
      type: set(['strawberry', 'vanilla'])
  rememberToken: true
  softDeletes: true
  timestamps: true

test_column_type4:
  columns:
    id:
      type: smallIncrements
    votes:
      type: smallInteger
    name:
      type: string(100)
    description:
      type: text
    sunrise:
      type: time
    sunrise_tz:
      type: timeTz
    added_on:
      type: timestamp
    added_on_tz:
      type: timestampTz
  softDeletesTz: true
  timestampsTz: true

test_column_type5:
  columns:
    id:
      type: tinyIncrements
    votes:
      type: tinyInteger
    votes_ubi:
      type: unsignedBigInteger
    votes_ui:
      type: unsignedInteger
    votes_umi:
      type: unsignedMediumInteger
    votes_usi:
      type: unsignedSmallInteger
    votes_uti:
      type: unsignedTinyInteger
    amount:
      type: unsignedDecimal(8, 2)
    uuid:
      type: uuid
    birth_year:
      type: year
```

**Comment by ucan-lab** [comment]
## 使用できるカラム修飾子のテスト用のyml

test_column_modifiers.yml

```
test_column_modifiers1:
  columns:
    id:
      type: integer
      autoIncrement: true
    name:
      type: string
      charset: utf8
      collation: utf8_unicode_ci
      comment: my comment
      default: test value
      nullable: true
    price:
      type: integer
      unsigned: true
    count:
      type: integer
      unsigned: true
    total_stored:
      type: integer
      storedAs: price * count
    total_virtual:
      type: integer
      virtualAs: price * count
    total_generated:
      type: integer
      generatedAs: price * count
    created_at:
      type: timestamp
      useCurrent: true
    seq:
      type: integer
      always: true
```
