### ISSUE TITLE
type のみ指定したい場合は省略して記述したい

### ISSUE THREAD

**Issue by ucan-lab** [ucan-lab/laravel-dacapo#19]
## 課題

```
test:
  columns:
    votes:
      type: bigInteger
    data:
      type: binary
    confirmed:
      type: boolean
    name:
      type: char(100)
```

これを

```
test:
  columns:
    votes: bigInteger
    data: binary
    confirm: boolean
    name: char(100)
```

こう定義できるようにしたい。
