### ISSUE TITLE
カラムタイプの引数指定方法の改善

### ISSUE THREAD

**Issue by ucan-lab** [ucan-lab/laravel-dacapo#81]
https://twitter.com/mpyw/status/1181183258068783106?s=20

## 現在

```
price:
  type: decimal(8, 2)
```

## 改修後

```
price:
  type: decimal
  args: [8, 2]
```

## エイリアス

```
timestamps:
  args: [0]
softDeletes:
  args: ['deleted_at', 0]

のエイリアスとして

timestamps: [0]
timestamps: 0
timestamps:
softDeletes: 'deleted_at'
softDeletes: ['deleted_at']
softDeletes: ['deleted_at', 0]
softDeletes:
```
