### ISSUE TITLE
onDelete is not reflected when onUpdate and onDelete are set.

### ISSUE THREAD

**Issue by ucan-lab** [ucan-lab/laravel-dacapo#98]
## Current

```
tasks:
  relations:
    - foreign: user_id
      references: id
      on: users
      onUpdate: cascade
      onDelete: cascade
  columns:
    id: bigIncrements
    user_id: unsignedBigInteger
    content: string
```

```
            $table->foreign('user_id')->references('id')->on('users')->onUpdate('cascade');
```

## After

```
            $table->foreign('user_id')->references('id')->on('users')->onUpdate('cascade')->onDelete('cascade');
```
